[package]
name = "acpica_sys"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = "0.10"
num_enum = { version = "0.7", default-features = false }


[build-dependencies]
tempdir = "0.3"
regex = "1.0"
cc = "1.2"

[features]
alloc = []
default = ["alloc"]
