[package]
name = "acpica"
version = "0.1.0"
edition = "2024"

[dependencies]
spin = { version = "0.10", default-features = false, features = ["once"] }


[build-dependencies]
tempdir = "0.3"
regex = "1.0"
cc = "1.2"

[features]
alloc = []
default = ["alloc"]
